-- ============================================================
-- Seed Public Subject Directory Highlights
--
-- Promote a curated set of non-project subjects so the public directory
-- starts with the intended high-level entities instead of specific repos.
-- ============================================================

BEGIN;

INSERT INTO public.subjects (
    slug,
    type,
    display_name,
    aliases,
    description,
    metadata,
    first_seen_at,
    last_seen_at,
    mention_count,
    status,
    directory_visible,
    section_slug,
    curation_priority,
    created_by,
    definition,
    homepage_url
)
VALUES
    (
        'agent:framework',
        'agent',
        'Agent 框架',
        ARRAY['agent framework', 'AI agent framework', 'agentic framework'],
        '用于构建、编排和运行 AI agent 的框架与运行时。',
        '{"source":"manual_review"}'::jsonb,
        CURRENT_DATE,
        CURRENT_DATE,
        0,
        'active',
        true,
        'agent',
        416,
        'approved_candidate',
        '用于构建、编排和运行 AI agent 的框架与运行时。',
        NULL
    ),
    (
        'agent:memory',
        'agent',
        'Agent 记忆',
        ARRAY['agent memory', 'memory for agents', 'agent memory system'],
        '让 AI agent 保留上下文、经验和长期状态的记忆能力与组件。',
        '{"source":"manual_review"}'::jsonb,
        CURRENT_DATE,
        CURRENT_DATE,
        0,
        'active',
        true,
        'agent',
        415,
        'approved_candidate',
        '让 AI agent 保留上下文、经验和长期状态的记忆能力与组件。',
        NULL
    ),
    (
        'company:nvidia',
        'company',
        '英伟达',
        ARRAY['NVIDIA', 'Nvidia'],
        'GPU、AI 芯片和加速计算龙头。',
        '{"source":"manual_review"}'::jsonb,
        CURRENT_DATE,
        CURRENT_DATE,
        0,
        'active',
        true,
        'company',
        414,
        'approved_candidate',
        'GPU、AI 芯片和加速计算龙头。',
        'https://www.nvidia.com'
    ),
    (
        'company:micron',
        'company',
        '美光',
        ARRAY['Micron', 'Micron Technology'],
        'AI 时代的存储芯片与内存厂商，受算力扩张影响明显。',
        '{"source":"manual_review"}'::jsonb,
        CURRENT_DATE,
        CURRENT_DATE,
        0,
        'active',
        true,
        'company',
        413,
        'approved_candidate',
        'AI 时代的存储芯片与内存厂商，受算力扩张影响明显。',
        'https://www.micron.com'
    ),
    (
        'company:zhipu',
        'company',
        '智谱',
        ARRAY['Zhipu', '智谱AI'],
        '中国大模型与智能体方向的重要公司之一。',
        '{"source":"manual_review"}'::jsonb,
        CURRENT_DATE,
        CURRENT_DATE,
        0,
        'active',
        true,
        'company',
        412,
        'approved_candidate',
        '中国大模型与智能体方向的重要公司之一。',
        'https://www.zhipuai.cn'
    ),
    (
        'company:xiaomi',
        'company',
        '小米公司',
        ARRAY['Xiaomi', 'Xiaomi Corporation'],
        '中国智能硬件、消费电子和生态链公司。',
        '{"source":"manual_review"}'::jsonb,
        CURRENT_DATE,
        CURRENT_DATE,
        0,
        'active',
        true,
        'company',
        411,
        'approved_candidate',
        '中国智能硬件、消费电子和生态链公司。',
        'https://www.mi.com'
    ),
    (
        'person:lei-jun',
        'person',
        '雷军',
        ARRAY['Lei Jun'],
        '小米创始人，消费电子和 AI 硬件话题的高关注人物。',
        '{"source":"manual_review"}'::jsonb,
        CURRENT_DATE,
        CURRENT_DATE,
        0,
        'active',
        true,
        'person',
        410,
        'approved_candidate',
        '小米创始人，消费电子和 AI 硬件话题的高关注人物。',
        'https://baike.baidu.com/item/%E9%9B%B7%E5%86%9B/33036'
    ),
    (
        'person:elon-musk',
        'person',
        '马斯克',
        ARRAY['Elon Musk'],
        '特斯拉、SpaceX、xAI 等公司的创始人，AI 与航天领域的重要人物。',
        '{"source":"manual_review"}'::jsonb,
        CURRENT_DATE,
        CURRENT_DATE,
        0,
        'active',
        true,
        'person',
        409,
        'approved_candidate',
        '特斯拉、SpaceX、xAI 等公司的创始人，AI 与航天领域的重要人物。',
        'https://x.com/elonmusk'
    ),
    (
        'company:openai',
        'company',
        'OpenAI',
        ARRAY['OpenAI'],
        '推动通用大模型、推理能力和 AI 产品化的核心公司之一。',
        '{"source":"manual_review"}'::jsonb,
        CURRENT_DATE,
        CURRENT_DATE,
        0,
        'active',
        true,
        'company',
        408,
        'approved_candidate',
        '推动通用大模型、推理能力和 AI 产品化的核心公司之一。',
        'https://openai.com'
    ),
    (
        'company:anthropic',
        'company',
        'Anthropic',
        ARRAY['Anthropic'],
        '聚焦安全、对齐和 Claude 系列模型的 AI 公司。',
        '{"source":"manual_review"}'::jsonb,
        CURRENT_DATE,
        CURRENT_DATE,
        0,
        'active',
        true,
        'company',
        407,
        'approved_candidate',
        '聚焦安全、对齐和 Claude 系列模型的 AI 公司。',
        'https://www.anthropic.com'
    ),
    (
        'company:deepseek',
        'company',
        'DeepSeek',
        ARRAY['DeepSeek', '深度求索'],
        '近期最受关注的大模型与推理能力代表之一。',
        '{"source":"manual_review"}'::jsonb,
        CURRENT_DATE,
        CURRENT_DATE,
        0,
        'active',
        true,
        'company',
        406,
        'approved_candidate',
        '近期最受关注的大模型与推理能力代表之一。',
        'https://www.deepseek.com'
    ),
    (
        'company:qwen',
        'company',
        '阿里通义',
        ARRAY['Qwen', '通义千问'],
        '阿里系的大模型与智能助手品牌。',
        '{"source":"manual_review"}'::jsonb,
        CURRENT_DATE,
        CURRENT_DATE,
        0,
        'active',
        true,
        'company',
        405,
        'approved_candidate',
        '阿里系的大模型与智能助手品牌。',
        'https://tongyi.aliyun.com'
    ),
    (
        'company:doubao',
        'company',
        '字节豆包',
        ARRAY['Doubao', '豆包'],
        '字节跳动在大模型和 AI 助手方向的重要产品品牌。',
        '{"source":"manual_review"}'::jsonb,
        CURRENT_DATE,
        CURRENT_DATE,
        0,
        'active',
        true,
        'company',
        404,
        'approved_candidate',
        '字节跳动在大模型和 AI 助手方向的重要产品品牌。',
        'https://www.doubao.com'
    ),
    (
        'company:google-deepmind',
        'company',
        'Google DeepMind',
        ARRAY['DeepMind', 'Google DeepMind'],
        'Google 旗下最重要的前沿模型与研究机构之一。',
        '{"source":"manual_review"}'::jsonb,
        CURRENT_DATE,
        CURRENT_DATE,
        0,
        'active',
        true,
        'company',
        403,
        'approved_candidate',
        'Google 旗下最重要的前沿模型与研究机构之一。',
        'https://deepmind.google'
    ),
    (
        'concept:ai-coding-assistant',
        'concept',
        'AI 编程助手',
        ARRAY['AI coding assistant', 'coding assistant'],
        '帮助开发者编写、补全、调试和审查代码的 AI 能力与产品方向。',
        '{"source":"manual_review"}'::jsonb,
        CURRENT_DATE,
        CURRENT_DATE,
        0,
        'active',
        true,
        'concept',
        402,
        'approved_candidate',
        '帮助开发者编写、补全、调试和审查代码的 AI 能力与产品方向。',
        NULL
    ),
    (
        'concept:multimodal-model',
        'concept',
        '多模态模型',
        ARRAY['multimodal model', 'vision-language model'],
        '同时理解文本、图像、音频或视频的基础模型方向。',
        '{"source":"manual_review"}'::jsonb,
        CURRENT_DATE,
        CURRENT_DATE,
        0,
        'active',
        true,
        'concept',
        401,
        'approved_candidate',
        '同时理解文本、图像、音频或视频的基础模型方向。',
        NULL
    )
ON CONFLICT (slug) DO UPDATE SET
    type = EXCLUDED.type,
    display_name = EXCLUDED.display_name,
    aliases = EXCLUDED.aliases,
    description = EXCLUDED.description,
    metadata = EXCLUDED.metadata,
    first_seen_at = LEAST(public.subjects.first_seen_at, EXCLUDED.first_seen_at),
    last_seen_at = GREATEST(public.subjects.last_seen_at, EXCLUDED.last_seen_at),
    mention_count = GREATEST(public.subjects.mention_count, EXCLUDED.mention_count),
    status = EXCLUDED.status,
    directory_visible = EXCLUDED.directory_visible,
    section_slug = EXCLUDED.section_slug,
    curation_priority = EXCLUDED.curation_priority,
    created_by = EXCLUDED.created_by,
    definition = EXCLUDED.definition,
    homepage_url = EXCLUDED.homepage_url;

COMMIT;
